version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    command: npm run serve
    ports:
      - "51821:51821/tcp"
      - "${WG_PORT:51822-51950}:${WG_PORT:51822-51950}/udp"
    volumes:
      - ./src/:/app/
    environment: 
      - PASSWORD=${PASSWORD:-1}
      - WG_PORT=${WG_PORT:51822}
      - WG_PORTS=${WG_PORT:51822-51950}
      # - WG_HOST=127.0.0.1
      # - WG_MTU=1360
