version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    command: npm run serve
    ports:
      - "51819:51821/tcp"
      - "51820-51950:51820-51950/udp"
    volumes:
      - ./src/:/app/
    environment: 
      # - PASSWORD=
      - WG_PORT=51820
      - WG_PORTs=51950-51950
      - WG_HOST=127.0.0.1
      - WG_MTU=1360
